paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  yaml_destination_file: 'data.json'
serialization_source: 'file'  # 'file' or 'object'
operations:
  - deserialize
  - serialize
  - convert